name: Terraform Plan

on:
  workflow_dispatch:
  
env:
  WORKING_DIR: 'example'
  ARM_CLIENT_ID : ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET : ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID : ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID : ${{ secrets.AZURE_TENANT_ID }}
  TF_VERSION: 1.4.6
  #VARS_FILE: dev.tfvars
  
jobs:  
  terraform_plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    #container:
    defaults:
      run:
        shell: bash
        working-directory: ./${{ env.WORKING_DIR }}
        
    steps:    
      - name: checkout
        uses: actions/checkout@v2
        
      - name: Set Env
        run: |
          echo: "PLAN_FILE=${GITHUB_REF##*/}-dev.tfplan" >> $GITHUB_ENV
          echo: "STATE_FILE=${GITHUB_REF##*/}.terraform.tfstate" >> GITHUB_ENV
           
      - name: login
        uses: azure/login@v2
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          
      - name: terraform init
        run: terraform init -backend-config=key=${env.STATE_FILE} -input=false 
          


