name: Terraform Plan

on:
  #workflow_dispatch:
  
env:
  WORKING_DIR: 'example'
  ARM_CLIENT_ID : ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET : ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID : ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID : ${{ secrets.AZURE_TENANT_ID }}
  TF_VERSION: 1.4.6
  VARS_FILE: dev.tfvars
  
jobs:  
  terraform_plan:
    name: Terraform Plan
    runs-on: [unbuntu-latest]
    container:
    defaults:
      run:
        shell: bash
        working-directory: ./${{ env.WORKING_DIR }}
    


